/**
 * Tests for the file encryption pipeline — session key wrap/unwrap,
 * metadata encrypt/decrypt, and the hierarchical key chain.
 *
 * Crypto v2 Phase 2b: every asymmetric wrap is now a hybrid of
 * X25519 + ML-KEM-768. Users + files carry HybridPublicKeys /
 * HybridPrivateKeys pairs; the wrap helpers derive a combined AEAD
 * key via HKDF over both shared secrets.
 */

import { describe, it, expect } from "vitest";
import { toBase64 } from "./utils";
import {
  generateSessionKey,
  encryptMetadata,
  decryptMetadata,
  generateHierarchicalKeypair,
  wrapSessionKeyToFile,
  unwrapSessionKeyFromFile,
  wrapPrivateHierarchicalKeyForUser,
  unwrapPrivateHierarchicalKey,
  wrapParentKeysClaim,
  unwrapParentKeysClaim,
} from "./file-crypto";

// Minimal "user" factory — each party in these tests owns a hybrid
// hierarchical keypair (same shape a real user has). In production
// users' keypairs are generated by `generateKeypairs` in keys.ts;
// re-using `generateHierarchicalKeypair` here is fine because the
// underlying primitives + serialization are identical.
function makeUser() {
  return generateHierarchicalKeypair();
}

describe("session key wrap/unwrap (hybrid)", () => {
  const owner = makeUser();
  const hier = generateHierarchicalKeypair();
  const sessionKey = generateSessionKey();

  it("round-trips session key through file wrap", () => {
    const { encryptedSessionKeyByFile, sessionKeyNonce } = wrapSessionKeyToFile(
      sessionKey,
      hier.publicKeys,
      owner.privateKeys.x25519,
    );
    const unwrapped = unwrapSessionKeyFromFile(
      encryptedSessionKeyByFile,
      sessionKeyNonce,
      owner.publicKeys.x25519,
      hier.privateKeys,
    );
    expect(toBase64(unwrapped)).toBe(toBase64(sessionKey));
  });

  it("wrong hier private keys fail to unwrap", () => {
    const { encryptedSessionKeyByFile, sessionKeyNonce } = wrapSessionKeyToFile(
      sessionKey,
      hier.publicKeys,
      owner.privateKeys.x25519,
    );
    const wrongHier = generateHierarchicalKeypair();
    expect(() =>
      unwrapSessionKeyFromFile(
        encryptedSessionKeyByFile,
        sessionKeyNonce,
        owner.publicKeys.x25519,
        wrongHier.privateKeys,
      ),
    ).toThrow();
  });
});

describe("metadata encrypt/decrypt (symmetric)", () => {
  const sessionKey = generateSessionKey();
  const meta = { name: "test.pdf", type: "application/pdf", size: 12345 };

  it("round-trips metadata", () => {
    const encrypted = encryptMetadata(meta, sessionKey);
    const decrypted = decryptMetadata(encrypted, sessionKey);
    expect(decrypted).toEqual(meta);
  });

  it("wrong key fails", () => {
    const encrypted = encryptMetadata(meta, sessionKey);
    const wrongKey = generateSessionKey();
    expect(() => decryptMetadata(encrypted, wrongKey)).toThrow();
  });
});

describe("hierarchical key chain (hybrid)", () => {
  const owner = makeUser();
  const recipient = makeUser();
  const hier = generateHierarchicalKeypair();

  it("round-trips private hier key through user wrap", () => {
    const wrapped = wrapPrivateHierarchicalKeyForUser(
      hier.privateKeys,
      recipient.publicKeys,
      owner.privateKeys.x25519,
    );
    const unwrapped = unwrapPrivateHierarchicalKey(
      wrapped,
      owner.publicKeys.x25519,
      recipient.privateKeys.x25519,
      recipient.privateKeys.kem,
    );
    expect(unwrapped.x25519).toBe(hier.privateKeys.x25519);
    expect(unwrapped.kem).toBe(hier.privateKeys.kem);
  });

  it("unwrapping without the ML-KEM private half fails", () => {
    // Preserves the core claim of hybrid: an attacker who recovers
    // X25519 secrets alone still can't unwrap (ML-KEM decap requires
    // the KEM private key).
    const wrapped = wrapPrivateHierarchicalKeyForUser(
      hier.privateKeys,
      recipient.publicKeys,
      owner.privateKeys.x25519,
    );
    const wrongKem = generateHierarchicalKeypair();
    expect(() =>
      unwrapPrivateHierarchicalKey(
        wrapped,
        owner.publicKeys.x25519,
        recipient.privateKeys.x25519,  // correct X25519 half
        wrongKem.privateKeys.kem,      // WRONG ML-KEM half
      ),
    ).toThrow();
  });
});

describe("parent_keys_claim chain (hybrid)", () => {
  const owner = makeUser();
  const parentHier = generateHierarchicalKeypair();
  const childHier = generateHierarchicalKeypair();
  const childSessionKey = generateSessionKey();

  it("round-trips child session key + priv hier through parent claim", () => {
    const claim = wrapParentKeysClaim(
      childSessionKey,
      childHier.privateKeys,
      parentHier.publicKeys,
      owner.privateKeys.x25519,
    );
    const unwrapped = unwrapParentKeysClaim(
      claim,
      owner.publicKeys.x25519,
      parentHier.privateKeys,
    );
    expect(toBase64(unwrapped.sessionKey)).toBe(toBase64(childSessionKey));
    expect(unwrapped.childPrivateHierarchicalKeys.x25519).toBe(childHier.privateKeys.x25519);
    expect(unwrapped.childPrivateHierarchicalKeys.kem).toBe(childHier.privateKeys.kem);
  });

  it("wrong parent key fails", () => {
    const claim = wrapParentKeysClaim(
      childSessionKey,
      childHier.privateKeys,
      parentHier.publicKeys,
      owner.privateKeys.x25519,
    );
    const wrongParent = generateHierarchicalKeypair();
    expect(() =>
      unwrapParentKeysClaim(claim, owner.publicKeys.x25519, wrongParent.privateKeys),
    ).toThrow();
  });
});
